(cd "c:/users/casey/documents/github/6.945-project")
(load "load")
(init)
(type-extract 3)
(type-extract #t)
(type-extract +)
(define x 4)
(type-extract (+ 3 4))
(type-extract (if (> x 3) #f 8))
(define a "happy")
(type-extract a)
(define (f x) (+ x 3))
(type-extract (f 4))
(type-extract ((lambda (x) (+ x 3)) 4))
(define (fact n)
  (if (<= n 1)
      1
      (* n (fact (- n 1)))))
(type-extract fact)
(define (fib n)
  (if (<= n 2)
      1
      (+ (fib (- n 1)) (fib (- n 2)))))
(type-extract fib)